# Nginx partial config to ensure PHP has the necessary
# environment variables available. Copy or symlink this
# into your `/etc/nginx/conf.d/` or similar directory.

fastcgi_param VOTING_DB_PATH '../voting.sqlite3';
fastcgi_param PORKBUN_API_TOKEN '';
fastcgi_param PORKBUN_SECRET_API_TOKEN '';
